import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";

const Home = () => {
  const handleOnBannerBtnClick = () => {
    console.log("hi banner button");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Background image"
            width={700}
            height={400}
          />
        </div>
        <div className={styles.cardLayout}>
          <Card
            className={styles.card}
            name="Dark Horse Coffee"
            href="/coffee-store/darkhorse-coffee"
            imgUrl="/static/hero-image.png"
          />
          <Card
            className={styles.card}
            name="Dark Horse Coffee"
            href="/coffee-store/darkhorse-coffee"
            imgUrl="/static/hero-image.png"
          />
          <Card
            className={styles.card}
            name="Dark Horse Coffee"
            href="/coffee-store/darkhorse-coffee"
            imgUrl="/static/hero-image.png"
          />
        </div>
      </main>
    </div>
  );
};

export default Home;
