import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/banner";
import Card from "../components/card";
import { fetchCoffeeStores } from "../lib/coffee-stores";
import useTrackLocation from "../hooks/use-track-location";
import { useEffect, useState } from "react";

export const getStaticProps = async (context) => {
  const staticCoffeeStores = await fetchCoffeeStores();
  return {
    props: { staticCoffeeStores },
  };
};

const Home = ({ staticCoffeeStores }) => {
  const [nearbyCoffeeStores, setNearbyCoffeeStores] = useState([]);
  const { handleTrackLocation, latLong, locationErrorMsg, isFindingLocation } =
    useTrackLocation();

  useEffect(() => {
    async function fetchNearbyCoffeeStores() {
      if (latLong) {
        try {
          const fetchedCoffeeStores = await fetchCoffeeStores(
            latLong,
            30,
            true
          );
          setNearbyCoffeeStores(fetchedCoffeeStores);
        } catch (error) {
          console.log(error);
        }
      }
    }

    fetchNearbyCoffeeStores();
  }, [latLong]);

  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
  };

  const generateCoffeeStoreCards = (coffeeStores) => {
    return coffeeStores.map((coffeeStore) => (
      <Card
        key={`${coffeeStore.id}`}
        name={coffeeStore.name}
        imgUrl={
          coffeeStore.imgUrl ||
          "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
        }
        href={`/coffee-store/${coffeeStore.id}`}
      />
    ));
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={isFindingLocation ? "Locating..." : "View stores nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        {locationErrorMsg.length > 0 ? (
          <p>Something went wrong: {locationErrorMsg}</p>
        ) : null}
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            alt="Background image"
            width={700}
            height={400}
          />
        </div>
        {nearbyCoffeeStores.length > 0 && (
          <div>
            <h2 className={styles.heading2}>Stores near me</h2>
            <div className={styles.cardLayout}>
              {generateCoffeeStoreCards(nearbyCoffeeStores)}
            </div>
          </div>
        )}
        {staticCoffeeStores.length > 0 && (
          <div>
            <h2 className={styles.heading2}>Toronto stores</h2>
            <div className={styles.cardLayout}>
              {generateCoffeeStoreCards(staticCoffeeStores)}
            </div>
          </div>
        )}
      </main>
    </div>
  );
};

export default Home;
